# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Jobs.proto for package 'demo'

require 'grpc'
require 'Jobs_pb'

module Demo
  module Jobs
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'demo.Jobs'

      rpc :GetJob, ::Demo::GetJobReq, ::Demo::GetJobResp
    end

    Stub = Service.rpc_stub_class
  end
end
